Salesforce:
  user: "integrador.salesforce@volcan.cl"
  pass: "1nt3gr4c10n9NrbpIu5blFB6D06ZbQpFAV12"
  clientId: "3MVG9xOCXq4ID1uEpciKJS9ESKN_dV5YiJcFBpO_r_0gV9Jfh07nefxOSN9k_A.0H4tlXK_5e66ZeVFYAv7Vd"
  clientSecret: "4AA402B99F4189F60C580676CA3876E09E6B76E899A1D2A210C25E6BBBA5806D"
  tokenUrl: "https://login.salesforce.com/services/oauth2/token"
  datosFijos:
    developerName: "VM_OrdenCompra"
    pricebook2Id: "01so0000000FzWtAAK"
    clienteNoEncontrado: "001PF00000UHbhpYAD"
    productoNoEncontrado: "01tPF00000ApisTYAR"
    pricebookEntryId: "01uPF000008ADYrYAO"
    regionPorDefecto: "Metropolitana de Santiago"

errorEmailTo: "mulesoft@alercesdigital.com,lvera@volcan.cl,ext.rcasella@volcan.cl"

SodimacXML:
  UNs: "AVSA,FIBR,VOLC"
  user_AVSA: "96848750-7|96966990-0"
  pass_AVSA: "B8D24FB8D047BDDD6B36644611CED170"
  user_FIBR: "77524300-7|96966990-0"
  pass_FIBR: "04370C176B6CA46B41E1A7186DA981FB"
  user_VOLC: "90209000-2|96966990-0"
  pass_VOLC: "3F2FB6A3258781BD561CF926F7AE296E"
  wsSoapSec: "wWS3fymoLd9nmo5EP39+2w=="
  rut_AVSA: "96848750-7"
  rut_FIBR: "77524300-7"
  rut_VOLC: "90209000-2"

SodimacGCP:
  privateKeyId: "5b67a88f0b06559e03a9594df8dd575ef71537e7"
  clientId: "103295598726765143616"
  clientEmail: "prch-provider-volcan@fal-corp-mrch-prchord-prod.iam.gserviceaccount.com"
  privateKey: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDDd6J0Ta6Dook1\nsO3UJud/kXJroIngqDKIFqxKhyxALGogZqzJttQtYLEcB3KqnyrRxylyYiJ5JZFX\nc1d0g0drBgjC+hEcVaKca5RbX/iFzuhR1iIq00EYPgrkiY2lxT6mpnu4kIJGvPA8\njhwKQIwXKdm64yT2+H+zoUSfGdVWz2ipTDv365OBOaVIfbIT+rhpHwYNLbbvYUsn\nG6FeHMEhhJL2sFPmitgJVlrRL3SLKAIaIWX7ZYDwyNpndt9zryDbfjC/nHEBLOPL\nT92U5IZNlPb7uDI10bZJ4X4TQ2ppEmMzzwOzpxyB1Wa1fUw1zk6cS8R2zz2lbA+q\n7aPaTJeHAgMBAAECggEADxYZuZF3tnzOy3aqmuUE/9yRXZ5k/3joq+ylqZVOcTmJ\nJPna78qm2UXAOOIxeg4rRBVAeeD6Uvb3Hvr6m5yFef/COo8KAqTW/LmoGESLYVB7\nfKCvv5xq4Fy36U529BdwL9tjnlzqh4+N/y58s/Hdau0PYZQ/rLjrQ+L4V+Td79As\n3l4SsuaDoWnOrMLyvAOCWi8HpWm/NBBYv7fU9dpamO4XqrFMW6DEsmAvH3n4yQUL\nerX1PvaHW1/OfZtjFyfCa7HcNcr8e5XBWlalu3wPN5R7hM3oH2h1+jGjByTDIO/w\nDYhshAy3j6ad79LxKIRRTOyx1lDV6dOVIhTWUM8jcQKBgQDw34ClBr7YyGjry75T\n76RdSNuHLs2VKUMtSBlSO75R2aDBFQ0uPz7Ivx5qLXYjZIzQfYZF4ClZYoNTZlbq\nBF5Jm7QpkmV/S4Vyx1w/t9q3vHlzxIp4gfGd8/ajY0NPKBnzuRdPT8DYX2eaJRGZ\n2mcuhSSTWWnqwawA1iLkIfn6OQKBgQDPviXI9QU/Cu9E0hYhVG+KqkpjJE9b0F0i\n//KTRcAPgCJim+rhYhXb+SqIgne+DkVfekJv5LVFOpAieGFiML+B/1joSonsBbqL\nj6hs768L2sghlS6W6CrZHBaz0b+NvZ8oiiE508IMZ0Vckf7qIJQ6mSmfhFMVB6YT\ni3+xb24fvwKBgQCyDqYMV+YwXkWhOOWjKp04ECmnzqNORkhQauG89kkEPHonASbT\nLxF8WDtlheG03Blz7baaZNBsMPSfbCGHsF76zszphjzdUrh9Vn4M5B4cgIjPWVR7\nLKOtfbCuqywQkbZNgl+G04/c4vm06v4N23M24lldS1WOokhB/gmg1rTxkQKBgQC2\nBCc9DJk9JEqB5QSozT8xooSsmurBSi3gdZrHOIzPx/fYqD3CndsDMiv3EUDzD7Pu\ntMMzIJNGhco1uX2xt36D2wO9+1kep+JLV2I9mD+pxlYlPn1kkSTBtx+ZDASmnuat\ncWEtNoFFttIKCozr/AGD2iCi+CCHQ31akJYgE77MJwKBgG2SYfbHBzyA+0uEsp8B\nefCykgLMdwEaNKKqANHnwJhS+PkeAs12zWwG00Zchp9OsksPYowbnNSkVSRxgoxX\n2rIGvOYY0gFrNzVSaVaimxP7DvqpQISZoC+H28V4EorVE/w7xEat07YnamELGfDk\nl7k1P17gUrmuiswyNb59sxpW\n-----END PRIVATE KEY-----\n"
  projectId: "fal-corp-mrch-prchord-prod"
  subscriptionName: "prch-provider-volcan"
  status: "1,4,5,20"

IDP:
  host: "idp-rt.us-east-1.anypoint.mulesoft.com"
  port: "443"
  basePath: "/"
  protocol: "HTTPS"
  timeout: "30000"
  clientId: "![K5n3GTBb6ogx/fqVQ0Ky8j+ribGmh/++SXCE4qsJlUR0d6d5E2qTuYQ/BqJuhRD7]"
  clientSecret: "![ZktWZcpDb3bWRgI7ET8bhbBFbWYgaRIR2dUG2+tKEujzY7q4X+hhzpcNIclxoVKe]"
  tokenUrl: "https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token"
  maxRetry: "10"
  timeBetweenRetry: "5000"

Outlook:
  baseUrl: "https://graph.microsoft.com/v1.0"
  clientId: "![aRHFKd8J1tSahwNJda6v7EPrhyE/WLlzf+mR9ea1mHJqdb70ENlbg02xwQdM72p0]"
  clientSecret: "![wKVC4tN5bJH0rpnm2TpKX2WZjVoMSJGFDM3Dy6oDcykn05ZrGGbNAdfZPDjGnZid]"
  tokenUrl: "https://login.microsoftonline.com/70d6839a-fa81-48e1-991e-1302e0329802/oauth2/v2.0/token"
  scopes: "https://graph.microsoft.com/.default"
  userId: "![hHSNJV9B/nP6oZ+Y6EaXLsm1vW0tHfMNo6Z0mIKrhoTHXO4F3QmxjbL9S7vEiFtB]"
  mailFolderId: "AQMkAGU4MDk3OGIwLTMxZDUtNGJmOC1iMGZkLWMxYTUzYTYwNWNhMwAuAAADJNXPnPaHf0mm3cIcETpv5gEAUaC0IXEBb0KsiZY53F0v7gAAAgEMAAAA"
#ordenes_compras@volcan.cl

SAP:
  username: "![hCDL0CaIaNxtlIObhjcbag==]"
  password: "![Wu51dtTOtfr+RWgfmp3LQjISidd8WEh7zJ2dH7EG8tQ=]"
  systemNumber: "00"
  clientId: "400"
  host: "172.16.88.35"
  bapiName: "ZMF_B2B_BRF"

MySQL:
  host: "172.16.90.55"
  port: "3306"
  username: "usermatrizprecios"
  password: ".Us3rm4trizprec10s."
  db: "matriz_precios"